### ISSUE TITLE
[OAuth] 첫번째 로그인 시 401 bug

### ISSUE THREAD

**Issue by hochan222** [transcendence42/ft_transcendence#104]
<img src="https://user-images.githubusercontent.com/22424891/125618139-d8427d35-d3d7-409f-919d-1f28ea2b4bd0.png" height="150px"/>

아이디가 잘 생성이 되었지만 브라우저 새로고침 전까지는 401 error가 뜹니다.
새로고침하면 잘됨.

```
[Nest] 53028   - 07/14/2021, 8:55:29 PM   [ExceptionsHandler] The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client. +77923ms
TokenError: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.
    at FtStrategy.OAuth2Strategy.parseErrorResponse (/Users/tonybyeon/Desktop/ft_transcendence/back/node_modules/passport-oauth2/lib/strategy.js:372:12)
    at FtStrategy.OAuth2Strategy._createOAuthError (/Users/tonybyeon/Desktop/ft_transcendence/back/node_modules/passport-oauth2/lib/strategy.js:419:16)
    at /Users/tonybyeon/Desktop/ft_transcendence/back/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /Users/tonybyeon/Desktop/ft_transcendence/back/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/Users/tonybyeon/Desktop/ft_transcendence/back/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Users/tonybyeon/Desktop/ft_transcendence/back/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by hochan222** [comment]
#54

**Comment by hochan222** [comment]
```js
  createUser(details: UserDetails) {
    const user = this.usersService.create({
      userID: details.username,
      nickname: details.username,
      avatar: details.photos[0]['value'],
    });
    return user;
  }
```

createUser 함수에서 user 반환을 안해서 생기는 문제였다.

```js
  async validateUser(details: UserDetails) {
    const { username } = details;
    const user: User | null = await this.usersService.findOne(username);
    if (user) {
      console.log('login success');
      return user;
    }
    const newUser = await this.createUser(details);
    return newUser;
  }
```
 
user 반환을 하지 않으니 당연히 newUser 가 빈값일 수 밖에 없다.
